### ISSUE TITLE
.env

### ISSUE THREAD

**Issue by jamalnggau1** [DavidRomanovizc/DatingBot#3]
I'm having a hard time filling in the .env file, please explain in more detail

**Comment by DavidRomanovizc** [comment]
```python
# Your telegram ID
ADMINS=440415604
# Bot token, you need to write to BotFather and create a bot
BOT_TOKEN=66a045b452102c59d840ec097d59d9467e13a3f34f6494e539ffd32c1bb35f18
# Don't change this
ip=localhost

# You need create a database, I used posgtresql
DB_USER = User 
DB_PASS = example
DB_HOST = localhost # Don't change this
DB_NAME = postgresql # or something else

# If you are not a citizen of the Russian Federation, then it will be difficult to fill in these variables
wallet=
qiwi=
qiwi_p_pub=
qiwi_p_sec=

```
I hope I explained it clearly

**Comment by jamalnggau1** [comment]
Thank you in advance for answering

what if I am not a Russian citizen? can i not use this project?

**Comment by DavidRomanovizc** [comment]
> Thank you in advance for answering
> 
> what if I am not a Russian citizen? can i not use this project?

Just you will change payment system 

read the documentation
https://core.telegram.org/bots/payments

**Comment by vR4eslav** [comment]
> what if I am not a Russian citizen? can i not use this project?

I think you will have problems using the bot, since each file uses Russian. We are working on localization of the bot and the project on github

**Comment by jamalnggau1** [comment]
> > bagaimana jika saya bukan warga negara Rusia? bisakah saya tidak menggunakan proyek ini?
> 
> Saya pikir Anda akan mengalami masalah dalam menggunakan bot, karena setiap file menggunakan bahasa Rusia. Kami sedang mengerjakan pelokalan bot dan proyek di github

Thank you very much. please also change the payment system to paypal
