### ISSUE TITLE
erorr comands

### ISSUE THREAD

**Issue by cjobs23** [DavidRomanovizc/DatingBot#59]
hi.I have a startup problem
![image](https://user-images.githubusercontent.com/81418530/197389118-044e4ec9-f667-4fea-9e54-a005fc06456e.png)
![image](https://user-images.githubusercontent.com/81418530/197389143-f3573d91-e4a3-4a10-a773-62b0d8dad6a1.png)

**Comment by DavidRomanovizc** [comment]
Hello, firstly, you need to create a database (check in the readme in the Django section), secondly, you need to use the "/start" command, not "/stats".
