### ISSUE TITLE
Improve the unblocking purchase system

### ISSUE THREAD

**Issue by DavidRomanovizc** [DavidRomanovizc/DatingBot#75]
In the current code, the amount required for user self-unlock is hardcoded. We need to introduce a more flexible approach to this functionality. The proposed solution involves creating a new model that allows for dynamic modification of the unlock cost through the admin panel. Additionally, it is necessary to implement a status indicator for the price relevance, indicating whether the price is up to date or not.

https://github.com/DavidRomanovizc/DatingBot/blob/2372ade938c0df819c411451be2e4f04125b2a16/handlers/users/buy_unban.py#L13

**Comment by cybro-rob** [comment]
do you mean the django admin panel??

**Comment by DavidRomanovizc** [comment]
> do you mean the django admin panel??

No, we have an [admin panel](https://github.com/DavidRomanovizc/DatingBot/blob/main/handlers/users/admin_handlers.py)  right in the bot, but we use Django ORM, so we need to register the model in Django and add it to the admin panel.
